set_test_name()

beginning_of_test(2345)
    begin_test
      --
      set_paired_outputs_on
      --
      configure_can
      --
      wait_until_slim -- Booted into SLiM
      --
      input_dcc_basic_acc_pair(0, Deactivate)
      log(1 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(1, Activate)
      log(1 in transmitter 1 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(2, Deactivate)
      log(1 in transmitter 2 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(3, Activate)
      log(1 in transmitter 3 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(4, Deactivate)
      log(1 in transmitter 4 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(5, Activate)
      log(1 in transmitter 5 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(6, Activate)
      log(1 in transmitter 6 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(7, Activate)
      log(1 in transmitter 7 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(8, Deactivate)
      log(1 in transmitter 8 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(9, Activate)
      log(1 in transmitter 9 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(10, Deactivate)
      log(1 in transmitter 10 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(11, Activate)
      log(1 in transmitter 11 in Event Tx queue 0 in DCC packet queue)
      --
      log(Queue 24 individual Activation translated as pair 12 Deactivation)
      input_dcc_basic_acc(24, Activate)
      log(1 in transmitter 12 in Event Tx queue 0 in DCC packet queue)
      --
      log(Queue 26 individual Deactivation translated as pair 13 Activation)
      input_dcc_basic_acc(26, Deactivate)
      log(1 in transmitter 13 in Event Tx queue 0 in DCC packet queue)
      --
      input_dcc_basic_acc_pair(14, Deactivate)
      log(1 in transmitter 14 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(15, Activate)
      log(1 in transmitter 15 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(16, Activate)
      log(1 in transmitter 16 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(17, Activate)
      log(1 in transmitter 17 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(18, Activate)
      log(1 in transmitter 18 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(19, Activate)
      log(1 in transmitter 19 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(20, Activate)
      log(1 in transmitter 20 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(21, Activate)
      log(1 in transmitter 21 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(22, Activate)
      log(1 in transmitter 22 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(23, Activate)
      log(1 in transmitter 23 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(24, Activate)
      log(1 in transmitter 24 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(25, Activate)
      log(1 in transmitter 25 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(26, Activate)
      log(1 in transmitter 26 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(27, Activate)
      log(1 in transmitter 27 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(28, Activate)
      log(1 in transmitter 28 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(29, Activate)
      log(1 in transmitter 29 in Event Tx queue 0 in DCC packet queue)
      input_dcc_extnd_acc(30, 42)
      log(1 in transmitter 30 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(31, Activate)
      log(1 in transmitter 31 in Event Tx queue 0 in DCC packet queue)
      --
      input_dcc_basic_acc_pair(101, Activate)
      log(1 in transmitter 31 in Event Tx queue 1 in DCC packet queue)
      input_dcc_basic_acc_pair(102, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 2 in DCC packet queue)
      input_dcc_basic_acc_pair(103, Activate)
      log(1 in transmitter 31 in Event Tx queue 3 in DCC packet queue)
      input_dcc_basic_acc_pair(104, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 4 in DCC packet queue)
      input_dcc_basic_acc_pair(105, Activate)
      log(1 in transmitter 31 in Event Tx queue 5 in DCC packet queue)
      input_dcc_basic_acc_pair(106, Activate)
      log(1 in transmitter 31 in Event Tx queue 6 in DCC packet queue)
      input_dcc_basic_acc_pair(107, Activate)
      log(1 in transmitter 31 in Event Tx queue 7 in DCC packet queue)
      input_dcc_basic_acc_pair(108, Activate)
      log(1 in transmitter 31 in Event Tx queue 8 in DCC packet queue)
      input_dcc_basic_acc_pair(109, Activate)
      log(1 in transmitter 31 in Event Tx queue 9 in DCC packet queue)
      input_dcc_basic_acc_pair(110, Activate)
      log(1 in transmitter 31 in Event Tx queue 10 in DCC packet queue)
      input_dcc_basic_acc_pair(111, Activate)
      log(1 in transmitter 31 in Event Tx queue 11 in DCC packet queue)
      input_dcc_basic_acc_pair(112, Activate)
      log(1 in transmitter 31 in Event Tx queue 12 in DCC packet queue)
      input_dcc_basic_acc_pair(113, Activate)
      log(1 in transmitter 31 in Event Tx queue 13 in DCC packet queue)
      input_dcc_basic_acc_pair(114, Activate)
      log(1 in transmitter 31 in Event Tx queue 14 in DCC packet queue)
      input_dcc_basic_acc_pair(115, Activate)
      log(1 in transmitter 31 in Event Tx queue 15 in DCC packet queue)
      input_dcc_basic_acc_pair(116, Activate)
      log(1 in transmitter 31 in Event Tx queue 16 in DCC packet queue)
      input_dcc_basic_acc_pair(117, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 17 in DCC packet queue)
      input_dcc_basic_acc_pair(118, Activate)
      log(1 in transmitter 31 in Event Tx queue 18 in DCC packet queue)
      input_dcc_basic_acc_pair(119, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 19 in DCC packet queue)
      input_dcc_basic_acc_pair(120, Activate)
      log(1 in transmitter 31 in Event Tx queue 20 in DCC packet queue)
      input_dcc_basic_acc_pair(121, Activate)
      log(1 in transmitter 31 in Event Tx queue 21 in DCC packet queue)
      input_dcc_basic_acc_pair(122, Activate)
      log(1 in transmitter 31 in Event Tx queue 22 in DCC packet queue)
      input_dcc_basic_acc_pair(123, Activate)
      log(1 in transmitter 31 in Event Tx queue 23 in DCC packet queue)
      input_dcc_basic_acc_pair(124, Activate)
      log(1 in transmitter 31 in Event Tx queue 24 in DCC packet queue)
      input_dcc_basic_acc_pair(125, Activate)
      log(1 in transmitter 31 in Event Tx queue 25 in DCC packet queue)
      input_dcc_basic_acc_pair(126, Activate)
      log(1 in transmitter 31 in Event Tx queue 26 in DCC packet queue)
      input_dcc_basic_acc_pair(127, Activate)
      log(1 in transmitter 31 in Event Tx queue 27 in DCC packet queue)
      input_dcc_basic_acc_pair(128, Activate)
      log(1 in transmitter 31 in Event Tx queue 28 in DCC packet queue)
      input_dcc_basic_acc_pair(129, Activate)
      log(1 in transmitter 31 in Event Tx queue 29 in DCC packet queue)
      input_dcc_basic_acc_pair(130, Activate)
      log(1 in transmitter 31 in Event Tx queue 30 in DCC packet queue)
      input_dcc_basic_acc_pair(131, Activate)
      log(1 in transmitter 31 in Event Tx queue 31 in DCC packet queue)
      input_dcc_basic_acc_pair(132, Activate)
      log(1 in transmitter 31 in Event Tx queue 32 in DCC packet queue)
      input_dcc_basic_acc_pair(133, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 33 in DCC packet queue)
      input_dcc_basic_acc_pair(134, Activate)
      log(1 in transmitter 31 in Event Tx queue 34 in DCC packet queue)
      input_dcc_basic_acc_pair(135, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 35 in DCC packet queue)
      input_dcc_basic_acc_pair(136, Activate)
      log(1 in transmitter 31 in Event Tx queue 36 in DCC packet queue)
      input_dcc_basic_acc_pair(137, Activate)
      log(1 in transmitter 31 in Event Tx queue 37 in DCC packet queue)
      input_dcc_basic_acc_pair(138, Activate)
      log(1 in transmitter 31 in Event Tx queue 38 in DCC packet queue)
      input_dcc_basic_acc_pair(139, Activate)
      log(1 in transmitter 31 in Event Tx queue 39 in DCC packet queue)
      input_dcc_basic_acc_pair(140, Activate)
      log(1 in transmitter 31 in Event Tx queue 40 in DCC packet queue)
      input_dcc_basic_acc_pair(141, Activate)
      log(1 in transmitter 31 in Event Tx queue 41 in DCC packet queue)
      input_dcc_basic_acc_pair(142, Activate)
      log(1 in transmitter 31 in Event Tx queue 42 in DCC packet queue)
      input_dcc_basic_acc_pair(143, Activate)
      log(1 in transmitter 31 in Event Tx queue 43 in DCC packet queue)
      input_dcc_basic_acc_pair(144, Activate)
      log(1 in transmitter 31 in Event Tx queue 44 in DCC packet queue)
      input_dcc_basic_acc_pair(145, Activate)
      log(1 in transmitter 31 in Event Tx queue 45 in DCC packet queue)
      input_dcc_basic_acc_pair(146, Activate)
      log(1 in transmitter 31 in Event Tx queue 46 in DCC packet queue)
      input_dcc_extnd_acc(147, 99)
      log(1 in transmitter 31 in Event Tx queue 47 in DCC packet queue)
      input_dcc_basic_acc_pair(148, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 48 in DCC packet queue)
      input_dcc_basic_acc_pair(149, Activate)
      log(1 in transmitter 31 in Event Tx queue 49 in DCC packet queue)
      input_dcc_basic_acc_pair(150, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 50 in DCC packet queue)
      input_dcc_basic_acc_pair(151, Activate)
      log(1 in transmitter 31 in Event Tx queue 51 in DCC packet queue)
      input_dcc_basic_acc_pair(152, Activate)
      log(1 in transmitter 31 in Event Tx queue 52 in DCC packet queue)
      input_dcc_basic_acc_pair(153, Activate)
      log(1 in transmitter 31 in Event Tx queue 53 in DCC packet queue)
      input_dcc_basic_acc_pair(154, Activate)
      log(1 in transmitter 31 in Event Tx queue 54 in DCC packet queue)
      input_dcc_basic_acc_pair(155, Activate)
      log(1 in transmitter 31 in Event Tx queue 55 in DCC packet queue)
      input_dcc_basic_acc_pair(156, Activate)
      log(1 in transmitter 31 in Event Tx queue 56 in DCC packet queue)
      input_dcc_basic_acc_pair(157, Activate)
      log(1 in transmitter 31 in Event Tx queue 57 in DCC packet queue)
      input_dcc_basic_acc_pair(158, Activate)
      log(1 in transmitter 31 in Event Tx queue 58 in DCC packet queue)
      input_dcc_basic_acc_pair(159, Activate)
      log(1 in transmitter 31 in Event Tx queue 59 in DCC packet queue)
      input_dcc_basic_acc_pair(160, Activate)
      log(1 in transmitter 31 in Event Tx queue 60 in DCC packet queue)
      input_dcc_basic_acc_pair(161, Activate)
      log(1 in transmitter 31 in Event Tx queue 61 in DCC packet queue)
      input_dcc_basic_acc_pair(162, Activate)
      log(1 in transmitter 31 in Event Tx queue 62 in DCC packet queue)
      input_dcc_basic_acc_pair(163, Activate)
      log(1 in transmitter 31 in Event Tx queue 63 in DCC packet queue)
      --
      log(DCC packet 204 Deactivate discarded)
      input_dcc_basic_acc_pair(204, Deactivate)
      log(1 in transmitter 31 in Event Tx queue 63 in DCC packet queue)
      --
      wait for 1 ms;
      --
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   0, EN low)
      log(1 in transmitter 31 in Event Tx queue 62 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   1, EN low)
      log(1 in transmitter 31 in Event Tx queue 61 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   2, EN low)
      log(1 in transmitter 31 in Event Tx queue 60 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   3, EN low)
      log(1 in transmitter 31 in Event Tx queue 59 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   4, EN low)
      log(1 in transmitter 31 in Event Tx queue 58 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   5, EN low)
      log(1 in transmitter 31 in Event Tx queue 57 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   6, EN low)
      log(1 in transmitter 31 in Event Tx queue 56 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   7, EN low)
      log(1 in transmitter 31 in Event Tx queue 55 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   8, EN low)
      log(1 in transmitter 31 in Event Tx queue 54 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   9, EN low)
      log(1 in transmitter 31 in Event Tx queue 53 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  10, EN low)
      log(1 in transmitter 31 in Event Tx queue 52 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  11, EN low)
      log(1 in transmitter 31 in Event Tx queue 51 in DCC packet queue)
      --
      log(Tx 24 individual Activation translated as pair 12 Deactivation)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  12, EN low)
      log(1 in transmitter 31 in Event Tx queue 50 in DCC packet queue)
      --
      log(Tx 26 individual Deactivation translated as pair 13 Activation)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  13, EN low)
      log(1 in transmitter 31 in Event Tx queue 49 in DCC packet queue)
      --
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  14, EN low)
      log(1 in transmitter 31 in Event Tx queue 48 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  15, EN low)
      log(1 in transmitter 31 in Event Tx queue 47 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  16, EN low)
      log(1 in transmitter 31 in Event Tx queue 46 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  17, EN low)
      log(1 in transmitter 31 in Event Tx queue 45 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  18, EN low)
      log(1 in transmitter 31 in Event Tx queue 44 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  19, EN low)
      log(1 in transmitter 31 in Event Tx queue 43 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  20, EN low)
      log(1 in transmitter 31 in Event Tx queue 42 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  21, EN low)
      log(1 in transmitter 31 in Event Tx queue 41 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  22, EN low)
      log(1 in transmitter 31 in Event Tx queue 40 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  23, EN low)
      log(1 in transmitter 31 in Event Tx queue 39 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  24, EN low)
      log(1 in transmitter 31 in Event Tx queue 38 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  25, EN low)
      log(1 in transmitter 31 in Event Tx queue 37 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  26, EN low)
      log(1 in transmitter 31 in Event Tx queue 36 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  27, EN low)
      log(1 in transmitter 31 in Event Tx queue 35 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  28, EN low)
      log(1 in transmitter 31 in Event Tx queue 34 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  29, EN low)
      log(1 in transmitter 31 in Event Tx queue 33 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON1, 0, 0, 0, EN high,  30, EN low,
                                               42, Data)
      log(1 in transmitter 31 in Event Tx queue 32 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  31, EN low)
      log(1 in transmitter 31 in Event Tx queue 31 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 101, EN low)
      log(1 in transmitter 31 in Event Tx queue 30 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 102, EN low)
      log(1 in transmitter 31 in Event Tx queue 29 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 103, EN low)
      log(1 in transmitter 31 in Event Tx queue 28 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 104, EN low)
      log(1 in transmitter 31 in Event Tx queue 27 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 105, EN low)
      log(1 in transmitter 31 in Event Tx queue 26 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 106, EN low)
      log(1 in transmitter 31 in Event Tx queue 25 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 107, EN low)
      log(1 in transmitter 31 in Event Tx queue 24 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 108, EN low)
      log(1 in transmitter 31 in Event Tx queue 23 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 109, EN low)
      log(1 in transmitter 31 in Event Tx queue 22 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 110, EN low)
      log(1 in transmitter 31 in Event Tx queue 21 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 111, EN low)
      log(1 in transmitter 31 in Event Tx queue 20 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 112, EN low)
      log(1 in transmitter 31 in Event Tx queue 19 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 113, EN low)
      log(1 in transmitter 31 in Event Tx queue 18 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 114, EN low)
      log(1 in transmitter 31 in Event Tx queue 17 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 115, EN low)
      log(1 in transmitter 31 in Event Tx queue 16 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 116, EN low)
      log(1 in transmitter 31 in Event Tx queue 15 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 117, EN low)
      log(1 in transmitter 31 in Event Tx queue 14 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 118, EN low)
      log(1 in transmitter 31 in Event Tx queue 13 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 119, EN low)
      log(1 in transmitter 31 in Event Tx queue 12 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 120, EN low)
      log(1 in transmitter 31 in Event Tx queue 11 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 121, EN low)
      log(1 in transmitter 31 in Event Tx queue 10 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 122, EN low)
      log(1 in transmitter 31 in Event Tx queue 9 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 123, EN low)
      log(1 in transmitter 31 in Event Tx queue 8 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 124, EN low)
      log(1 in transmitter 31 in Event Tx queue 7 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 125, EN low)
      log(1 in transmitter 31 in Event Tx queue 6 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 126, EN low)
      log(1 in transmitter 31 in Event Tx queue 5 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 127, EN low)
      log(1 in transmitter 31 in Event Tx queue 4 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 128, EN low)
      log(1 in transmitter 31 in Event Tx queue 3 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 129, EN low)
      log(1 in transmitter 31 in Event Tx queue 2 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 130, EN low)
      log(1 in transmitter 31 in Event Tx queue 1 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 131, EN low)
      log(1 in transmitter 31 in Event Tx queue 0 in DCC packet queue)
      --
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 132, EN low)
      log(1 in transmitter 30 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 133, EN low)
      log(1 in transmitter 29 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 134, EN low)
      log(1 in transmitter 28 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 135, EN low)
      log(1 in transmitter 27 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 136, EN low)
      log(1 in transmitter 26 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 137, EN low)
      log(1 in transmitter 25 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 138, EN low)
      log(1 in transmitter 24 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 139, EN low)
      log(1 in transmitter 23 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 140, EN low)
      log(1 in transmitter 22 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 141, EN low)
      log(1 in transmitter 21 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 142, EN low)
      log(1 in transmitter 20 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 143, EN low)
      log(1 in transmitter 19 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 144, EN low)
      log(1 in transmitter 18 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 145, EN low)
      log(1 in transmitter 17 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 146, EN low)
      log(1 in transmitter 16 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON1, 0, 0, 0, EN high, 147, EN low,
                                               99, Data)
      log(1 in transmitter 15 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 148, EN low)
      log(1 in transmitter 14 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 149, EN low)
      log(1 in transmitter 13 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 150, EN low)
      log(1 in transmitter 12 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 151, EN low)
      log(1 in transmitter 11 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 152, EN low)
      log(1 in transmitter 10 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 153, EN low)
      log(1 in transmitter 9 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 154, EN low)
      log(1 in transmitter 8 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 155, EN low)
      log(1 in transmitter 7 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 156, EN low)
      log(1 in transmitter 6 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 157, EN low)
      log(1 in transmitter 5 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 158, EN low)
      log(1 in transmitter 4 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 159, EN low)
      log(1 in transmitter 3 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 160, EN low)
      log(1 in transmitter 2 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 161, EN low)
      log(1 in transmitter 1 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 162, EN low)
      log(1 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      --
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 163, EN low)
      log(0 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      --
      tx_check_for_no_message(1, DCC event)
      --
      input_dcc_basic_acc_pair(301, Activate)
      tx_wait_for_node_message(OPC_ASON, 0, 0, high_byte(301), EN high,
                                               low_byte(301), EN low)
      --
      input_dcc_basic_acc_pair(301, Deactivate)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, high_byte(301), EN high,
                                               low_byte(301), EN low)
      --
      tx_check_for_no_message(1, DCC event)
      --
end_of_test
