set_test_name()

beginning_of_test(912)
    begin_test
      --
      configure_can
      --
      wait_until_slim -- Booted into SLiM
      --
      input_dcc_basic_acc_pair(0, Deactivate)
      log(1 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(1, Activate)
      log(1 in transmitter 1 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(2, Deactivate)
      log(1 in transmitter 2 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(3, Activate)
      log(1 in transmitter 3 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(4, Deactivate)
      log(1 in transmitter 4 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(5, Activate)
      log(1 in transmitter 5 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(6, Activate)
      log(1 in transmitter 6 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(7, Activate)
      log(1 in transmitter 7 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(8, Deactivate)
      log(1 in transmitter 8 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(9, Activate)
      log(1 in transmitter 9 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(10, Deactivate)
      log(1 in transmitter 10 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(11, Activate)
      log(1 in transmitter 11 in Event Tx queue 0 in DCC packet queue)
      --
      log(DCC packet 201 Deactivate not queued as event for Tx)
      input_dcc_basic_acc(201, Deactivate)
      log(1 in transmitter 11 in Event Tx queue 0 in DCC packet queue)
      --
      log(Queue 24 individual Activation translated as pair 12 Deactivation)
      input_dcc_basic_acc(24, Activate)
      log(1 in transmitter 12 in Event Tx queue 0 in DCC packet queue)
      --
      log(DCC packet 202 Deactivate not queued as event for Tx)
      input_dcc_basic_acc(202, Deactivate)
      log(1 in transmitter 12 in Event Tx queue 0 in DCC packet queue)
      --
      log(Queue 26 individual Activation translated as pair 13 Deactivation)
      input_dcc_basic_acc(26, Activate)
      log(1 in transmitter 13 in Event Tx queue 0 in DCC packet queue)
      log(DCC packet queue insert and extract wrapped)
      --
      input_dcc_basic_acc_pair(14, Deactivate)
      log(1 in transmitter 14 in Event Tx queue 0 in DCC packet queue)
      input_dcc_basic_acc_pair(15, Activate)
      log(1 in transmitter 15 in Event Tx queue 0 in DCC packet queue)
      log(Event Tx queue insert wrapped)
      --
      input_dcc_basic_acc_pair(16, Deactivate)
      log(1 in transmitter 16 in Event Tx queue 0 in DCC packet queue)
      --
      input_dcc_basic_acc_pair(101, Activate)
      log(1 in transmitter 16 in Event Tx queue 1 in DCC packet queue)
      input_dcc_basic_acc_pair(102, Deactivate)
      log(1 in transmitter 16 in Event Tx queue 2 in DCC packet queue)
      input_dcc_basic_acc_pair(103, Activate)
      log(1 in transmitter 16 in Event Tx queue 3 in DCC packet queue)
      input_dcc_basic_acc_pair(104, Deactivate)
      log(1 in transmitter 16 in Event Tx queue 4 in DCC packet queue)
      input_dcc_basic_acc_pair(105, Activate)
      log(1 in transmitter 16 in Event Tx queue 5 in DCC packet queue)
      input_dcc_basic_acc_pair(106, Activate)
      log(1 in transmitter 16 in Event Tx queue 6 in DCC packet queue)
      input_dcc_basic_acc_pair(107, Activate)
      log(1 in transmitter 16 in Event Tx queue 7 in DCC packet queue)
      input_dcc_basic_acc_pair(108, Activate)
      log(1 in transmitter 16 in Event Tx queue 8 in DCC packet queue)
      input_dcc_basic_acc_pair(109, Activate)
      log(1 in transmitter 16 in Event Tx queue 9 in DCC packet queue)
      input_dcc_basic_acc_pair(110, Activate)
      log(1 in transmitter 16 in Event Tx queue 10 in DCC packet queue)
      input_dcc_basic_acc_pair(111, Activate)
      log(1 in transmitter 16 in Event Tx queue 11 in DCC packet queue)
      input_dcc_basic_acc_pair(112, Activate)
      log(1 in transmitter 16 in Event Tx queue 12 in DCC packet queue)
      input_dcc_basic_acc_pair(113, Activate)
      log(1 in transmitter 16 in Event Tx queue 13 in DCC packet queue)
      log(DCC packet queue insert wrapped)
      --
      input_dcc_basic_acc_pair(114, Activate)
      log(1 in transmitter 16 in Event Tx queue 14 in DCC packet queue)
      input_dcc_basic_acc_pair(115, Activate)
      log(1 in transmitter 16 in Event Tx queue 15 in DCC packet queue)
      input_dcc_basic_acc_pair(116, Activate)
      log(1 in transmitter 16 in Event Tx queue 16 in DCC packet queue)
      --
      log(DCC packet 204 Deactivate discarded)
      input_dcc_basic_acc_pair(204, Deactivate)
      log(1 in transmitter 16 in Event Tx queue 16 in DCC packet queue)
      --
      wait for 1 ms;
      --
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   0, EN low)
      log(1 in transmitter 16 in Event Tx queue 15 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   1, EN low)
      log(1 in transmitter 16 in Event Tx queue 14 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   2, EN low)
      log(1 in transmitter 16 in Event Tx queue 13 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   3, EN low)
      log(1 in transmitter 16 in Event Tx queue 12 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   4, EN low)
      log(1 in transmitter 16 in Event Tx queue 11 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   5, EN low)
      log(1 in transmitter 16 in Event Tx queue 10 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   6, EN low)
      log(1 in transmitter 16 in Event Tx queue 9 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   7, EN low)
      log(1 in transmitter 16 in Event Tx queue 8 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   8, EN low)
      log(1 in transmitter 16 in Event Tx queue 7 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   9, EN low)
      log(1 in transmitter 16 in Event Tx queue 6 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  10, EN low)
      log(1 in transmitter 16 in Event Tx queue 5 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  11, EN low)
      log(1 in transmitter 16 in Event Tx queue 4 in DCC packet queue)
      --
      log(Tx 24 individual Activation translated as pair 12 Deactivation)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  12, EN low)
      log(1 in transmitter 16 in Event Tx queue 3 in DCC packet queue)
      --
      log(Tx 26 individual Activation translated as pair 13 Deactivation)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  13, EN low)
      log(DCC packet queue extract wrapped)
      log(1 in transmitter 16 in Event Tx queue 2 in DCC packet queue)
      --
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  14, EN low)
      log(1 in transmitter 16 in Event Tx queue 1 in DCC packet queue)
      log(Event Tx queue insert and extract wrapped)
      --
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  15, EN low)
      log(1 in transmitter 16 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  16, EN low)
      log(1 in transmitter 15 in Event Tx queue 0 in DCC packet queue)
      --
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 101, EN low)
      log(1 in transmitter 14 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 102, EN low)
      log(1 in transmitter 13 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 103, EN low)
      log(1 in transmitter 12 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 104, EN low)
      log(1 in transmitter 11 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 105, EN low)
      log(1 in transmitter 10 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 106, EN low)
      log(1 in transmitter 9 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 107, EN low)
      log(1 in transmitter 8 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 108, EN low)
      log(1 in transmitter 7 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 109, EN low)
      log(1 in transmitter 6 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 110, EN low)
      log(1 in transmitter 5 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 111, EN low)
      log(1 in transmitter 4 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 112, EN low)
      log(1 in transmitter 3 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 113, EN low)
      log(1 in transmitter 2 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 114, EN low)
      log(1 in transmitter 1 in Event Tx queue 0 in DCC packet queue)
      log(Event Tx queue extract wrapped)
      --
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 115, EN low)
      log(1 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 116, EN low)
      log(0 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      --
      tx_check_for_no_message(1, DCC event)
      --
      input_dcc_basic_acc_pair(301, Activate)
      tx_wait_for_node_message(OPC_ASON, 0, 0, high_byte(301), EN high,
                                               low_byte(301), EN low)
      --
      input_dcc_basic_acc_pair(301, Deactivate)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, high_byte(301), EN high,
                                               low_byte(301), EN low)
      --
      tx_check_for_no_message(1, DCC event)
      --
end_of_test
