set_test_name()

beginning_of_test(3100)
    begin_test
      --
      set_paired_outputs_on
      --
      configure_can
      --
      wait_until_slim -- Booted into SLiM
      --
      input_dcc_basic_acc_pair(0, Deactivate)
      log(1 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      --
      input_dcc_basic_acc_pair( 1, Activate)
      input_dcc_basic_acc_pair( 2, Deactivate)
      input_dcc_basic_acc_pair( 3, Activate)
      input_dcc_basic_acc_pair( 4, Deactivate)
      input_dcc_basic_acc_pair( 5, Activate)
      input_dcc_basic_acc_pair( 6, Activate)
      input_dcc_basic_acc_pair( 7, Activate)
      input_dcc_basic_acc_pair( 8, Deactivate)
      input_dcc_basic_acc_pair( 9, Activate)
      input_dcc_basic_acc_pair(10, Deactivate)
      input_dcc_basic_acc_pair(11, Activate)
      --
      log(Queue 24 individual Activation translated as pair 12 Deactivation)
      input_dcc_basic_acc(24, Activate)
      --
      log(Queue 26 individual Deactivation translated as pair 13 Activation)
      input_dcc_basic_acc(26, Deactivate)
      --
      input_dcc_basic_acc_pair(14, Deactivate)
      input_dcc_basic_acc_pair(15, Activate)
      input_dcc_basic_acc_pair(16, Activate)
      input_dcc_basic_acc_pair(17, Activate)
      input_dcc_basic_acc_pair(18, Activate)
      input_dcc_basic_acc_pair(19, Activate)
      input_dcc_basic_acc_pair(20, Activate)
      input_dcc_basic_acc_pair(21, Activate)
      input_dcc_basic_acc_pair(22, Activate)
      input_dcc_basic_acc_pair(23, Activate)
      input_dcc_basic_acc_pair(24, Activate)
      input_dcc_basic_acc_pair(25, Activate)
      input_dcc_basic_acc_pair(26, Activate)
      input_dcc_basic_acc_pair(27, Activate)
      input_dcc_basic_acc_pair(28, Activate)
      input_dcc_basic_acc_pair(29, Activate)
      input_dcc_extnd_acc(30, 42)
      input_dcc_basic_acc_pair(31, Activate)
      input_dcc_basic_acc_pair(32, Activate)
      input_dcc_basic_acc_pair(33, Activate)
      input_dcc_basic_acc_pair(34, Activate)
      input_dcc_basic_acc_pair(35, Activate)
      input_dcc_basic_acc_pair(36, Activate)
      input_dcc_basic_acc_pair(37, Activate)
      input_dcc_basic_acc_pair(38, Activate)
      input_dcc_basic_acc_pair(39, Activate)
      input_dcc_basic_acc_pair(40, Activate)
      input_dcc_basic_acc_pair(41, Activate)
      input_dcc_basic_acc_pair(42, Activate)
      input_dcc_basic_acc_pair(43, Activate)
      input_dcc_basic_acc_pair(44, Activate)
      input_dcc_basic_acc_pair(45, Activate)
      input_dcc_basic_acc_pair(46, Activate)
      input_dcc_basic_acc_pair(47, Activate)
      input_dcc_basic_acc_pair(48, Activate)
      input_dcc_basic_acc_pair(49, Activate)
      input_dcc_basic_acc_pair(50, Activate)
      input_dcc_basic_acc_pair(51, Activate)
      input_dcc_basic_acc_pair(52, Activate)
      input_dcc_basic_acc_pair(53, Activate)
      input_dcc_basic_acc_pair(54, Activate)
      input_dcc_basic_acc_pair(55, Activate)
      input_dcc_basic_acc_pair(56, Activate)
      input_dcc_basic_acc_pair(57, Activate)
      input_dcc_basic_acc_pair(58, Activate)
      input_dcc_basic_acc_pair(59, Activate)
      input_dcc_basic_acc_pair(60, Activate)
      input_dcc_basic_acc_pair(61, Activate)
      input_dcc_basic_acc_pair(62, Activate)
      input_dcc_basic_acc_pair(63, Activate)
      log(1 in transmitter 63 in Event Tx queue 0 in DCC packet queue)
      --
      input_dcc_basic_acc_pair(101, Activate)
      input_dcc_basic_acc_pair(102, Deactivate)
      input_dcc_basic_acc_pair(103, Activate)
      input_dcc_basic_acc_pair(104, Deactivate)
      input_dcc_basic_acc_pair(105, Activate)
      input_dcc_basic_acc_pair(106, Activate)
      input_dcc_basic_acc_pair(107, Activate)
      input_dcc_basic_acc_pair(108, Activate)
      input_dcc_basic_acc_pair(109, Activate)
      input_dcc_basic_acc_pair(110, Activate)
      input_dcc_basic_acc_pair(111, Activate)
      input_dcc_basic_acc_pair(112, Activate)
      input_dcc_basic_acc_pair(113, Activate)
      input_dcc_basic_acc_pair(114, Activate)
      input_dcc_basic_acc_pair(115, Activate)
      input_dcc_basic_acc_pair(116, Activate)
      input_dcc_basic_acc_pair(117, Deactivate)
      input_dcc_basic_acc_pair(118, Activate)
      input_dcc_basic_acc_pair(119, Deactivate)
      input_dcc_basic_acc_pair(120, Activate)
      input_dcc_basic_acc_pair(121, Activate)
      input_dcc_basic_acc_pair(122, Activate)
      input_dcc_basic_acc_pair(123, Activate)
      input_dcc_basic_acc_pair(124, Activate)
      input_dcc_basic_acc_pair(125, Activate)
      input_dcc_basic_acc_pair(126, Activate)
      input_dcc_basic_acc_pair(127, Activate)
      input_dcc_basic_acc_pair(128, Activate)
      input_dcc_basic_acc_pair(129, Activate)
      input_dcc_basic_acc_pair(130, Activate)
      input_dcc_basic_acc_pair(131, Activate)
      input_dcc_basic_acc_pair(132, Activate)
      input_dcc_basic_acc_pair(133, Deactivate)
      input_dcc_basic_acc_pair(134, Activate)
      input_dcc_basic_acc_pair(135, Deactivate)
      input_dcc_basic_acc_pair(136, Activate)
      input_dcc_basic_acc_pair(137, Activate)
      input_dcc_basic_acc_pair(138, Activate)
      input_dcc_basic_acc_pair(139, Activate)
      input_dcc_basic_acc_pair(140, Activate)
      input_dcc_basic_acc_pair(141, Activate)
      input_dcc_basic_acc_pair(142, Activate)
      input_dcc_basic_acc_pair(143, Activate)
      input_dcc_basic_acc_pair(144, Activate)
      input_dcc_basic_acc_pair(145, Activate)
      input_dcc_basic_acc_pair(146, Activate)
      input_dcc_extnd_acc(147, 99)
      input_dcc_basic_acc_pair(148, Deactivate)
      input_dcc_basic_acc_pair(149, Activate)
      input_dcc_basic_acc_pair(150, Deactivate)
      input_dcc_basic_acc_pair(151, Activate)
      input_dcc_basic_acc_pair(152, Activate)
      input_dcc_basic_acc_pair(153, Activate)
      input_dcc_basic_acc_pair(154, Activate)
      input_dcc_basic_acc_pair(155, Activate)
      input_dcc_basic_acc_pair(156, Activate)
      input_dcc_basic_acc_pair(157, Activate)
      input_dcc_basic_acc_pair(158, Activate)
      input_dcc_basic_acc_pair(159, Activate)
      input_dcc_basic_acc_pair(160, Activate)
      input_dcc_basic_acc_pair(161, Activate)
      input_dcc_basic_acc_pair(162, Activate)
      input_dcc_basic_acc_pair(163, Activate)
      log(1 in transmitter 63 in Event Tx queue 63 in DCC packet queue)
      --
      log(DCC packet 204 Deactivate discarded)
      input_dcc_basic_acc_pair(204, Deactivate)
      --
      wait for 1 ms;
      --
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   0, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   1, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   2, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   3, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   4, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   5, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   6, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   7, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,   8, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,   9, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  10, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  11, EN low)
      --
      log(Tx 24 individual Activation translated as pair 12 Deactivation)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  12, EN low)
      --
      log(Tx 26 individual Deactivation translated as pair 13 Activation)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  13, EN low)
      --
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high,  14, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  15, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  16, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  17, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  18, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  19, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  20, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  21, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  22, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  23, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  24, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  25, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  26, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  27, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  28, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  29, EN low)
      tx_wait_for_node_message(OPC_ASON1, 0, 0, 0, EN high, 30, EN low,
                                               42, Data)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  31, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  32, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  33, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  34, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  35, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  36, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  37, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  38, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  39, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  40, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  41, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  42, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  43, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  44, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  45, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  46, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  47, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  48, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  49, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  50, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  51, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  52, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  53, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  54, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  55, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  56, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  57, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  58, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  59, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  60, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  61, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  62, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high,  63, EN low)
      log(1 in transmitter 63 in Event Tx queue 0 in DCC packet queue)
      --
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 101, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 102, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 103, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 104, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 105, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 106, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 107, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 108, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 109, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 110, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 111, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 112, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 113, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 114, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 115, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 116, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 117, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 118, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 119, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 120, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 121, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 122, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 123, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 124, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 125, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 126, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 127, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 128, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 129, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 130, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 131, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 132, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 133, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 134, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 135, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 136, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 137, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 138, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 139, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 140, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 141, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 142, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 143, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 144, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 145, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 146, EN low)
      tx_wait_for_node_message(OPC_ASON1, 0, 0, 0, EN high, 147, EN low,
                                               99, Data)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 148, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 149, EN low)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, 0, EN high, 150, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 151, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 152, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 153, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 154, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 155, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 156, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 157, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 158, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 159, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 160, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 161, EN low)
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 162, EN low)
      log(1 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      --
      tx_wait_for_node_message(OPC_ASON, 0, 0, 0, EN high, 163, EN low)
      log(0 in transmitter 0 in Event Tx queue 0 in DCC packet queue)
      --
      tx_check_for_no_message(1, DCC event)
      --
      input_dcc_basic_acc_pair(301, Activate)
      tx_wait_for_node_message(OPC_ASON, 0, 0, high_byte(301), EN high,
                                               low_byte(301), EN low)
      --
      input_dcc_basic_acc_pair(301, Deactivate)
      tx_wait_for_node_message(OPC_ASOF, 0, 0, high_byte(301), EN high,
                                               low_byte(301), EN low)
      --
      tx_check_for_no_message(1, DCC event)
      --
end_of_test
